# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['desktop/server.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('core', 'core'),  # Core logic
    ],
    hiddenimports=[
        # uvicorn
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        # fastapi
        'fastapi.middleware.cors',
        # core modules (auto-tessell pipeline)
        'core',
        'core.schemas',
        'core.analyzer',
        'core.analyzer.file_reader',
        'core.analyzer.geometry_analyzer',
        'core.preprocessor',
        'core.preprocessor.pipeline',
        'core.preprocessor.repair',
        'core.preprocessor.remesh',
        'core.preprocessor.converter',
        'core.strategist',
        'core.strategist.tier_selector',
        'core.strategist.param_optimizer',
        'core.strategist.strategy_planner',
        'core.generator',
        'core.generator.pipeline',
        'core.generator.polymesh_writer',
        'core.generator.polyhedral',
        'core.generator.tier0_core',
        'core.generator.tier05_netgen',
        'core.generator.tier1_snappy',
        'core.generator.tier15_cfmesh',
        'core.generator.tier2_tetwild',
        'core.generator.openfoam_writer',
        'core.evaluator',
        'core.evaluator.quality_checker',
        'core.evaluator.native_checker',
        'core.evaluator.metrics',
        'core.evaluator.report',
        'core.evaluator.fidelity',
        'core.pipeline',
        'core.pipeline.orchestrator',
        'core.utils',
        'core.utils.logging',
        'core.utils.openfoam_utils',
        'core.utils.polymesh_reader',
        'core.utils.boundary_classifier',
        'core.utils.bc_writer',
        'core.utils.vtk_exporter',
        'core.utils.errors',
        'core.utils.parallel',
        'core.utils.profiler',
        # mesh libraries
        'trimesh',
        'pytetwild',
        'meshio',
        'pymeshfix',
        'pyacvd',
        'pyvista',
        'numpy',
        'scipy',
        'scipy.spatial',
        'scipy.spatial.transform._rotation_groups',
        'pydantic',
        'structlog',
        'click',
        'rich',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='auto-tessell-server',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True, # Set to False for windowed app, but helpful for debugging
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='server',
)
