"""Tier HOHQMesh: 고차(High-Order) 구조화 Hex 메쉬 생성.

HOHQMesh (High Order Hex-Quad Mesh) 바이너리를 사용하여
직육면체 도메인(background grid)의 구조화 Hex 메쉬를 생성한다.

적합한 사용 사례:
- 단순 직육면체 채널 유동
- 배경 격자(background grid) 기반 유동 도메인
- 고차 스펙트럴 요소법(SEM) 해석용 Hex 메쉬

제한 사항:
- 복잡한 3D CAD 기하학 직접 메싱 불가
- STL 표면 적합(conforming) 메쉬 불가
- 박스/채널 형태 도메인만 지원
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from typing import Any

import numpy as np

from core.schemas import MeshStrategy, TierAttempt
from core.utils.logging import get_logger

logger = get_logger(__name__)

TIER_NAME = "tier_hohqmesh"

# HOHQMesh 바이너리 경로 (플랫폼별 확장자)
_HOHQMESH_BIN_NAME = "HOHQMesh.exe" if sys.platform == "win32" else "HOHQMesh"
_HOHQMESH_BIN = Path(__file__).parent.parent.parent / "bin" / _HOHQMESH_BIN_NAME


def _find_hohqmesh() -> Path | None:
    """HOHQMesh 바이너리를 찾는다.

    탐색 순서:
      1. 프로젝트 ``bin/`` 디렉터리 (인스톨러가 번들한 위치)
      2. PATH
      3. Windows 설치 경로
    """
    if _HOHQMESH_BIN.exists():
        return _HOHQMESH_BIN

    # Windows: 추가 설치 경로 탐색
    if sys.platform == "win32":
        for win_dir in (
            Path(os.environ.get("PROGRAMFILES", r"C:\Program Files")) / "AutoTessell" / "bin",
            Path(r"C:\AutoTessell\bin"),
        ):
            p = win_dir / "HOHQMesh.exe"
            if p.exists():
                return p

    found = shutil.which("HOHQMesh") or shutil.which("HOHQMesh.exe")
    if found:
        return Path(found)
    return None


def _build_control_file(
    strategy: MeshStrategy,
    output_mesh_path: Path,
    work_dir: Path,
) -> Path:
    """HOHQMesh .control 파일을 생성한다.

    STL의 bounding box를 기반으로 Background Grid를 자동 계산한다.

    Args:
        strategy: MeshStrategy (domain 정보 포함).
        output_mesh_path: 출력 메쉬 경로 (.mesh 파일).
        work_dir: 작업 디렉터리.

    Returns:
        생성된 .control 파일 경로.
    """
    params = strategy.tier_specific_params
    domain = strategy.domain

    # 도메인 경계 결정
    if domain is not None:
        x0 = [float(domain.min[0]), float(domain.min[1]), float(domain.min[2])]
        x1 = [float(domain.max[0]), float(domain.max[1]), float(domain.max[2])]
    else:
        # 기본 단위 박스
        x0 = [0.0, 0.0, 0.0]
        x1 = [1.0, 1.0, 1.0]

    # 격자 크기 결정
    target_size = float(strategy.surface_mesh.target_cell_size)
    dx = [
        max(target_size, (x1[0] - x0[0]) / 20),
        max(target_size, (x1[1] - x0[1]) / 20),
        max(target_size, (x1[2] - x0[2]) / 20),
    ]

    # 사용자 지정 격자 크기 오버라이드
    if "hohq_dx" in params:
        dx = [float(params["hohq_dx"])] * 3
    if "hohq_n_cells" in params:
        n = int(params["hohq_n_cells"])
        dx = [
            (x1[0] - x0[0]) / n,
            (x1[1] - x0[1]) / n,
            (x1[2] - x0[2]) / n,
        ]

    # 각 방향 셀 수
    n_cells = [
        max(1, int(round((x1[i] - x0[i]) / dx[i])))
        for i in range(3)
    ]

    # 고차 다항식 차수
    poly_order = int(params.get("hohq_poly_order", 1))

    # 높이 방향 (3=z 방향 압출)
    extrusion_dir = int(params.get("hohq_extrusion_dir", 3))
    extrusion_height = float(x1[extrusion_dir - 1] - x0[extrusion_dir - 1])
    extrusion_subdivisions = n_cells[extrusion_dir - 1]

    # 2D 베이스 격자 설정 (x-y 평면)
    dir_map = {3: (0, 1), 1: (1, 2), 2: (0, 2)}
    d1, d2 = dir_map[extrusion_dir]

    mesh_path_str = str(output_mesh_path).replace("\\", "/")

    control_content = f"""%
% HOHQMesh control file — auto-generated by AutoTessell
% Domain: [{x0[0]:.4g}, {x0[1]:.4g}, {x0[2]:.4g}] → [{x1[0]:.4g}, {x1[1]:.4g}, {x1[2]:.4g}]
%
\\begin{{CONTROL_INPUT}}

   \\begin{{RUN_PARAMETERS}}
      mesh file name   = {mesh_path_str}
      plot file name   = none
      stats file name  = none
      mesh file format = ISM
      polynomial order = {poly_order}
      plot file format = skeleton
   \\end{{RUN_PARAMETERS}}

   \\begin{{MESH_PARAMETERS}}
      element type = hex
   \\end{{MESH_PARAMETERS}}

   \\begin{{BACKGROUND_GRID}}
       x0 = [{x0[d1]:.6g}, {x0[d2]:.6g}, 0.0]
       dx = [{dx[d1]:.6g}, {dx[d2]:.6g}, 1.0]
       N  = [{n_cells[d1]}, {n_cells[d2]}, 1]
   \\end{{BACKGROUND_GRID}}

   \\begin{{SIMPLE_EXTRUSION}}
      direction          = {extrusion_dir}
      height             = {extrusion_height:.6g}
      subdivisions       = {extrusion_subdivisions}
      start surface name = bottom
      end surface name   = top
   \\end{{SIMPLE_EXTRUSION}}

   \\begin{{SPRING_SMOOTHER}}
      smoothing            = ON
      smoothing type       = LinearAndCrossBarSpring
      number of iterations = 5
   \\end{{SPRING_SMOOTHER}}

\\end{{CONTROL_INPUT}}

\\end{{FILE}}
"""

    control_path = work_dir / "auto_tessell.control"
    control_path.write_text(control_content)

    logger.info(
        "hohqmesh_control_written",
        path=str(control_path),
        x0=x0, x1=x1,
        dx=dx, n_cells=n_cells,
        poly_order=poly_order,
    )
    return control_path


def _is_hex_connectivity(line: str) -> bool:
    """8개의 양의 정수로만 이루어진 줄인지 확인 (hex8 연결성 라인 식별).

    ISM 셀 블록에서 connectivity 라인은 1-indexed 정수 8개를 가진다.
    markers(6개), xyz(3개), face-name(문자열) 라인과 구별된다.
    """
    parts = line.split()
    if len(parts) != 8:
        return False
    try:
        return all(int(p) > 0 for p in parts)
    except ValueError:
        return False


def _parse_ism(ism_path: Path) -> tuple[np.ndarray, np.ndarray]:
    """HOHQMesh ISM 포맷 파싱 → (points, hex_cells).

    ISM 포맷 구조 (셀당 가변 길이):
      Line 1: n_nodes n_cells n_markers
      Lines 2..n_nodes+1: x y z (노드 좌표)
      Per cell (가변 길이, 경계 여부에 따라 다름):
        - Line 1: 8개의 1-indexed 노드 인덱스 (hex8 연결성)
        - Line 2: 6개의 면 마커 (0 or 1)
        - Lines 3+: 고차 노드 xyz / 면 이름 등 (경계 셀에만 존재)

    셀 연결성 라인은 "양의 정수 8개"로 식별 (가변 길이 대응).
    """
    lines = ism_path.read_text().splitlines()
    header = lines[0].split()
    n_nodes, n_cells = int(header[0]), int(header[1])

    # 노드 좌표
    points = np.array(
        [list(map(float, lines[i + 1].split())) for i in range(n_nodes)],
        dtype=np.float64,
    )

    # 셀 연결성: 양의 정수 8개인 라인만 추출
    cells_start = 1 + n_nodes
    hex_cells = []
    for line in lines[cells_start:]:
        if _is_hex_connectivity(line):
            indices = [int(v) - 1 for v in line.split()]  # 0-indexed
            hex_cells.append(indices)
            if len(hex_cells) == n_cells:
                break

    return points, np.array(hex_cells, dtype=np.int64)


def _ism_to_polymesh(ism_path: Path, case_dir: Path) -> dict[str, Any]:
    """HOHQMesh ISM 출력을 OpenFOAM polyMesh로 변환한다.

    ISM 포맷을 직접 파싱하여 hex → tet 분해 후 PolyMeshWriter로 변환.
    """
    from core.generator.polymesh_writer import PolyMeshWriter

    points, hex_cells = _parse_ism(ism_path)

    # hex → tet (Kuhn 분해: 6 tets per hex)
    all_tets = []
    for h in hex_cells:
        all_tets.extend([
            [h[0], h[1], h[3], h[4]],
            [h[1], h[2], h[3], h[6]],
            [h[1], h[3], h[4], h[6]],
            [h[4], h[5], h[6], h[1]],
            [h[4], h[6], h[7], h[3]],
            [h[3], h[4], h[6], h[1]],
        ])
    tet_cells = np.array(all_tets, dtype=np.int64)

    writer = PolyMeshWriter()
    stats = writer.write(points, tet_cells, case_dir)
    return stats


class TierHOHQMeshGenerator:
    """HOHQMesh 기반 고차 구조화 Hex 메쉬 생성기.

    단순한 직육면체 도메인에 대해 구조화 Hex 메쉬를 생성한다.
    HOHQMesh 바이너리가 설치되어 있어야 한다.

    주요 파라미터 (tier_specific_params):
        hohq_dx: float — 격자 간격 (기본: target_cell_size)
        hohq_n_cells: int — 방향당 셀 수 (hohq_dx보다 우선)
        hohq_poly_order: int — 고차 다항식 차수 (기본: 1)
        hohq_extrusion_dir: int — 압출 방향 (1=x, 2=y, 3=z, 기본: 3)
    """

    def run(
        self,
        strategy: MeshStrategy,
        preprocessed_path: Path,
        case_dir: Path,
    ) -> TierAttempt:
        """HOHQMesh 파이프라인을 실행한다."""
        t_start = time.monotonic()
        logger.info("tier_hohqmesh_start")

        # HOHQMesh 바이너리 확인
        hohqmesh_bin = _find_hohqmesh()
        if hohqmesh_bin is None:
            elapsed = time.monotonic() - t_start
            return TierAttempt(
                tier=TIER_NAME,
                status="failed",
                time_seconds=elapsed,
                error_message=(
                    "HOHQMesh 바이너리를 찾을 수 없습니다. "
                    "bin/HOHQMesh를 확인하세요."
                ),
            )

        try:
            with tempfile.TemporaryDirectory(prefix="autotessell_hohq_") as tmp_dir:
                work_dir = Path(tmp_dir)
                mesh_output = work_dir / "output.mesh"

                # .control 파일 생성
                control_path = _build_control_file(strategy, mesh_output, work_dir)

                # HOHQMesh 실행
                cmd = [str(hohqmesh_bin), "-f", str(control_path)]
                logger.info("hohqmesh_running", cmd=" ".join(cmd))

                timeout = int(strategy.tier_specific_params.get("hohq_timeout", 120))
                result = subprocess.run(
                    cmd,
                    capture_output=True,
                    text=True,
                    timeout=timeout,
                    cwd=str(work_dir),
                )

                if result.returncode != 0:
                    elapsed = time.monotonic() - t_start
                    logger.error(
                        "hohqmesh_failed",
                        returncode=result.returncode,
                        stderr=result.stderr[:500],
                    )
                    return TierAttempt(
                        tier=TIER_NAME,
                        status="failed",
                        time_seconds=elapsed,
                        error_message=f"HOHQMesh 실행 실패 (code={result.returncode}): {result.stderr[:200]}",
                    )

                # 출력 파일 확인
                if not mesh_output.exists():
                    # HOHQMesh는 때때로 .inp 또는 다른 확장자를 사용
                    candidates = list(work_dir.glob("*.mesh")) + list(work_dir.glob("*.inp"))
                    if not candidates:
                        elapsed = time.monotonic() - t_start
                        return TierAttempt(
                            tier=TIER_NAME,
                            status="failed",
                            time_seconds=elapsed,
                            error_message="HOHQMesh 출력 파일을 찾을 수 없습니다.",
                        )
                    mesh_output = candidates[0]

                # OpenFOAM polyMesh로 변환
                mesh_stats = _ism_to_polymesh(mesh_output, case_dir)

            elapsed = time.monotonic() - t_start
            logger.info(
                "tier_hohqmesh_success",
                elapsed=elapsed,
                mesh_stats=mesh_stats,
            )

            return TierAttempt(
                tier=TIER_NAME,
                status="success",
                time_seconds=elapsed,
            )

        except subprocess.TimeoutExpired:
            elapsed = time.monotonic() - t_start
            logger.error("hohqmesh_timeout", elapsed=elapsed)
            return TierAttempt(
                tier=TIER_NAME,
                status="failed",
                time_seconds=elapsed,
                error_message="HOHQMesh 타임아웃",
            )
        except Exception as exc:
            elapsed = time.monotonic() - t_start
            logger.exception("tier_hohqmesh_failed", error=str(exc))
            return TierAttempt(
                tier=TIER_NAME,
                status="failed",
                time_seconds=elapsed,
                error_message=f"Tier HOHQMesh 실패: {exc}",
            )
