// C++23 private actual-v2 authority-bound Native TRI+QUAD consumer.
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "native_volume_authority_bound_impl.hpp"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <map>
#include <set>
#include <stdexcept>
#include <string>
#include <vector>

namespace py=pybind11;
namespace {
struct P{double x{},y{},z{};};
P sub(P a,P b){return {a.x-b.x,a.y-b.y,a.z-b.z};}
P cross(P a,P b){return {a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x};}
double dot(P a,P b){return a.x*b.x+a.y*b.y+a.z*b.z;}
double norm(P a){return std::sqrt(dot(a,a));}
std::string txt(const py::dict&d,const char*k){return d.contains(k)&&!d[k].is_none()?py::str(d[k]).cast<std::string>():std::string{};}
bool flag(const py::dict&d,const char*k){return d.contains(k)&&!d[k].is_none()&&d[k].cast<bool>();}
bool hex64(const std::string&s){if(s.size()!=64)return false;return std::all_of(s.begin(),s.end(),[](char c){return(c>='0'&&c<='9')||(c>='a'&&c<='f');});}
py::dict reject(const char*r,std::int64_t req){py::dict d;d["accepted"]=false;d["status"]="native_tri_quad_authority_bound_rollback";d["reason"]=r;d["requested_layers"]=req;d["actual_layers"]=0;d["runtime_route"]="default_off";d["publication_eligible"]=false;d["route_calls"]=0;d["candidate_discarded"]=true;d["atomic_rollback"]=true;return d;}
std::vector<P> points(const py::sequence&o){std::vector<P>v;for(py::handle h:o){auto s=py::reinterpret_borrow<py::sequence>(h);if(py::len(s)!=3)throw std::invalid_argument("point_width");v.push_back({py::cast<double>(s[0]),py::cast<double>(s[1]),py::cast<double>(s[2])});}return v;}
std::vector<std::array<int,3>> tris(const py::sequence&o){std::vector<std::array<int,3>>v;for(py::handle h:o){auto s=py::reinterpret_borrow<py::sequence>(h);if(py::len(s)!=3)throw std::invalid_argument("triangle_width");v.push_back({py::cast<int>(s[0]),py::cast<int>(s[1]),py::cast<int>(s[2])});}return v;}
std::vector<std::array<int,4>> quads(const py::sequence&o){std::vector<std::array<int,4>>v;for(py::handle h:o){auto s=py::reinterpret_borrow<py::sequence>(h);if(py::len(s)!=4)throw std::invalid_argument("quad_width");v.push_back({py::cast<int>(s[0]),py::cast<int>(s[1]),py::cast<int>(s[2]),py::cast<int>(s[3])});}return v;}
template<size_t N>bool same(const std::vector<std::array<int,N>>&a,const std::vector<std::array<int,N>>&b){return a==b;}
bool samep(const std::vector<P>&a,const std::vector<P>&b){if(a.size()!=b.size())return false;for(size_t i=0;i<a.size();++i)if(a[i].x!=b[i].x||a[i].y!=b[i].y||a[i].z!=b[i].z)return false;return true;}
std::string ekey(int a,int b){if(a>b)std::swap(a,b);return std::to_string(a)+","+std::to_string(b);}
std::string fkey(int kind,const std::vector<int>&ids){auto x=ids;std::sort(x.begin(),x.end());std::string s=kind==3?"t:":"q:";for(int id:x)s+=std::to_string(id)+",";return s;}
double p95(std::vector<double>x){if(x.empty())return 0.;std::sort(x.begin(),x.end());size_t i=static_cast<size_t>(std::ceil(.95*x.size()))-1;return x[std::min(i,x.size()-1)];}
struct Face{int kind;std::vector<int>ids;};
struct M{int duplicate=0,nonmanifold=0,inverted=0,degenerate=0,self_intersection=0;double maxno=0,p95no=0,maxskew=0,p95skew=0,maxaspect=0,p95aspect=0,minjac=1e300;std::set<int>boundary;};
M measure(const std::vector<P>&p,const std::vector<std::array<int,3>>&t,const std::vector<std::array<int,4>>&q){
 M m;std::vector<Face>fs;for(const auto&x:t)fs.push_back({3,std::vector<int>(x.begin(),x.end())});for(const auto&x:q)fs.push_back({4,std::vector<int>(x.begin(),x.end())});
 std::set<std::string>seen;std::map<std::string,std::vector<std::pair<int,int>>>edges;std::vector<P>normals(fs.size());std::vector<double>sk,asp,no;
 for(size_t i=0;i<fs.size();++i){const auto&c=fs[i].ids;bool valid=c.size()==static_cast<size_t>(fs[i].kind);for(int id:c)if(id<0||static_cast<size_t>(id)>=p.size())valid=false;std::set<int>u(c.begin(),c.end());if(!valid||u.size()!=c.size()){++m.degenerate;continue;}if(!seen.insert(fkey(fs[i].kind,c)).second)++m.duplicate;P n{};if(fs[i].kind==3)n=cross(sub(p[c[1]],p[c[0]]),sub(p[c[2]],p[c[0]]));else n={cross(sub(p[c[1]],p[c[0]]),sub(p[c[2]],p[c[0]])).x+cross(sub(p[c[2]],p[c[0]]),sub(p[c[3]],p[c[0]])).x,cross(sub(p[c[1]],p[c[0]]),sub(p[c[2]],p[c[0]])).y+cross(sub(p[c[2]],p[c[0]]),sub(p[c[3]],p[c[0]])).y,cross(sub(p[c[1]],p[c[0]]),sub(p[c[2]],p[c[0]])).z+cross(sub(p[c[2]],p[c[0]]),sub(p[c[3]],p[c[0]])).z};double area=.5*norm(n);if(area<=1e-14){++m.degenerate;continue;}normals[i]=n;std::vector<double>le;for(size_t k=0;k<c.size();++k)le.push_back(norm(sub(p[c[(k+1)%c.size()]],p[c[k]])));double mn=*std::min_element(le.begin(),le.end()),mx=*std::max_element(le.begin(),le.end());if(mn<=1e-14){++m.degenerate;continue;}m.maxaspect=std::max(m.maxaspect,mx/mn);asp.push_back(mx/mn);m.minjac=std::min(m.minjac,area/(mx*mx));for(size_t k=0;k<c.size();++k){int u0=c[k],v=c[(k+1)%c.size()];edges[ekey(u0,v)].push_back({static_cast<int>(i),u0<v?1:-1});P a=sub(p[c[(k+c.size()-1)%c.size()]],p[c[k]]),b=sub(p[c[(k+1)%c.size()]],p[c[k]]);double den=norm(a)*norm(b);if(fs[i].kind==3)sk.push_back(.5*(1.-mn/mx));else if(den>1e-14)sk.push_back(std::abs(std::acos(std::max(-1.,std::min(1.,dot(a,b)/den)))*180./3.141592653589793-90.)/90.);}}
 for(const auto&[e,rows]:edges){if(rows.size()>2)m.nonmanifold++;if(rows.size()==1)m.boundary.insert(rows[0].first);if(rows.size()==2&&rows[0].second==rows[1].second)m.inverted++;}
 for(size_t i=0;i<fs.size();++i)for(size_t j=i+1;j<fs.size();++j){std::set<int>a(fs[i].ids.begin(),fs[i].ids.end()),b(fs[j].ids.begin(),fs[j].ids.end());bool share=false;for(int x:a)if(b.count(x))share=true;if(share)continue;P amin{1e300,1e300,1e300},amax{-1e300,-1e300,-1e300},bmin{1e300,1e300,1e300},bmax{-1e300,-1e300,-1e300};for(int id:fs[i].ids){const auto&z=p[id];amin.x=std::min(amin.x,z.x);amin.y=std::min(amin.y,z.y);amin.z=std::min(amin.z,z.z);amax.x=std::max(amax.x,z.x);amax.y=std::max(amax.y,z.y);amax.z=std::max(amax.z,z.z);}for(int id:fs[j].ids){const auto&z=p[id];bmin.x=std::min(bmin.x,z.x);bmin.y=std::min(bmin.y,z.y);bmin.z=std::min(bmin.z,z.z);bmax.x=std::max(bmax.x,z.x);bmax.y=std::max(bmax.y,z.y);bmax.z=std::max(bmax.z,z.z);}if(amin.x<bmax.x&&bmin.x<amax.x&&amin.y<bmax.y&&bmin.y<amax.y&&amin.z<bmax.z&&bmin.z<amax.z)m.self_intersection++;}
 for(const auto&[e,rows]:edges)if(rows.size()==2){P a=normals[rows[0].first],b=normals[rows[1].first];double den=norm(a)*norm(b);no.push_back(den>1e-14?std::acos(std::min(1.,std::abs(dot(a,b))/den))*180./3.141592653589793:90.);}
 m.maxskew=sk.empty()?0:*std::max_element(sk.begin(),sk.end());m.p95skew=p95(sk);m.p95aspect=p95(asp);m.maxno=no.empty()?0:*std::max_element(no.begin(),no.end());m.p95no=p95(no);return m;
}
bool producer(const py::dict&d,std::int64_t req){return flag(d,"lineage_complete")&&d.contains("actual_layers")&&d["actual_layers"].cast<std::int64_t>()==req&&d.contains("total_thickness")&&d["total_thickness"].cast<double>()>0&&d.contains("thickness_monotone")&&flag(d,"thickness_monotone")&&d.contains("growth_ratio_error")&&d["growth_ratio_error"].cast<double>()<=.02;}
bool ledger(const py::dict&d,const py::dict&a,std::set<std::string>&ids,std::map<std::string,std::string>&features,std::map<std::string,std::string>&patches,std::map<std::string,std::string>&groups){if(txt(d,"schema")!="native-tri-quad-source-ledger/v1"||!flag(d,"immutable")||!hex64(txt(d,"source_sha256"))||!d.contains("source_faces")||py::len(d["source_faces"])==0)return false;if(a.contains("source_sha256")&&txt(a,"source_sha256")!=txt(d,"source_sha256"))return false;for(py::handle h:py::reinterpret_borrow<py::sequence>(d["source_faces"])){py::dict f=py::reinterpret_borrow<py::dict>(h);for(const char*k:{"source_face_id","patch_id","feature_id","physical_group","component_id"})if(txt(f,k).empty())return false;std::string id=txt(f,"source_face_id");if(!ids.insert(id).second)return false;features[id]=txt(f,"feature_id");patches[id]=txt(f,"patch_id");groups[id]=txt(f,"physical_group");}return true;}
}
py::dict validate(const py::dict&a,const py::dict&o,const py::dict&l,const py::dict&prod,const py::sequence&bind,const py::sequence&bp_obj,const py::sequence&bt_obj,const py::sequence&bq_obj,const py::sequence&cp_obj,const py::sequence&ct_obj,const py::sequence&cq_obj,std::int64_t req,std::int64_t actual,const std::string&bd,const std::string&cd,bool quad_relabel,bool triangle_handoff,bool pair_plan_reordered){
 if(req<0||actual<0)return reject("negative_layer_count",req);
 if(!autotessell_native::authority_receipt_ready(a)||!autotessell_native::optimizer_receipt_ready(o,req)||actual!=req)return reject("receipt_or_partial_layer",req);
 std::set<std::string>ids,used;std::map<std::string,std::string>features,patches,groups;if(!ledger(l,a,ids,features,patches,groups))return reject("source_ledger_incomplete",req);
 auto bp=points(bp_obj);auto bt=tris(bt_obj);auto bq=quads(bq_obj);auto cp=points(cp_obj);auto ct=tris(ct_obj);auto cq=quads(cq_obj);
 if(quad_relabel)return reject("quad_relabel_rejected",req);
 if(triangle_handoff)return reject("triangle_handoff_rejected",req);
 if(pair_plan_reordered)return reject("pair_plan_reordered",req);
 if(req==0){if(!hex64(bd)||!hex64(cd)||bd!=cd||!samep(bp,cp)||!same(bt,ct)||!same(bq,cq))return reject("bl0_mixed_identity_mismatch",req);}
 else{if(!producer(prod,req))return reject("producer_certificate_incomplete",req);if(samep(bp,cp)&&same(bt,ct)&&same(bq,cq))return reject("tri_quad_clone_rejected",req);if(ct.empty()||cq.empty())return reject("mixed_topology_required",req);}
 std::set<std::string>outputs;int triout=0,quadout=0;double maxwall=0;std::vector<double>walls;
 for(py::handle h:bind){py::dict r=py::reinterpret_borrow<py::dict>(h);for(const char*k:{"source_edge","wall_edge","output_kind","output_face","feature","patch","physical_group","component","provenance"})if(txt(r,k).empty())return reject("direct_mixed_lineage_incomplete",req);std::string kind=txt(r,"output_kind");int id=-1;try{id=r["output_face"].cast<int>();}catch(...){return reject("output_face_invalid",req);}std::string out=kind+":"+std::to_string(id);if(!outputs.insert(out).second)return reject("output_binding_invalid",req);if(kind=="triangle"){if(id<0||static_cast<size_t>(id)>=ct.size()||txt(r,"source_face").empty())return reject("triangle_binding_invalid",req);++triout;std::string sf=txt(r,"source_face");if(!used.insert(sf).second||!ids.count(sf))return reject("source_face_consumption_invalid",req);}else if(kind=="quad"){if(id<0||static_cast<size_t>(id)>=cq.size()||txt(r,"source_face_a").empty()||txt(r,"source_face_b").empty())return reject("quad_binding_invalid",req);++quadout;std::string sa=txt(r,"source_face_a"),sb=txt(r,"source_face_b");if(sa==sb||!ids.count(sa)||!ids.count(sb)||!used.insert(sa).second||!used.insert(sb).second)return reject("quad_source_consumption_invalid",req);if(features[sa]!=features[sb]||patches[sa]!=patches[sb]||groups[sa]!=groups[sb])return reject("cross_boundary_pairing_rejected",req);}else return reject("mixed_output_kind_invalid",req);if(req>0){if(!r.contains("layer")||r["layer"].cast<int>()<1||!r.contains("wall_front_orthogonality_degrees"))return reject("wall_edge_binding_incomplete",req);double w=r["wall_front_orthogonality_degrees"].cast<double>();if(!std::isfinite(w)||w>25.)return reject("wall_front_quality_gate_failed",req);walls.push_back(w);maxwall=std::max(maxwall,w);}}
 if(req>0&&(used.size()!=ids.size()||outputs.size()!=ct.size()+cq.size()||triout==0||quadout==0))return reject("mixed_provenance_coverage_incomplete",req);
 M m;try{m=measure(cp,ct,cq);}catch(...){return reject("native_tri_quad_readback_failed",req);}if(m.duplicate||m.nonmanifold||m.inverted||m.degenerate||m.self_intersection)return reject("mixed_surface_topology_failed",req);if(m.minjac<=0||m.maxskew>.5||m.p95skew>.25||m.maxaspect>5||m.p95aspect>3||m.maxno>50||m.p95no>35)return reject("mixed_surface_quality_gate_failed",req);
 py::dict topo;topo["duplicate"]=m.duplicate;topo["non_manifold"]=m.nonmanifold;topo["inverted"]=m.inverted;topo["degenerate"]=m.degenerate;topo["self_intersection"]=m.self_intersection;topo["boundary_faces"]=m.boundary.size();py::dict q;q["max_skewness"]=m.maxskew;q["p95_skewness"]=m.p95skew;q["max_tangent_aspect"]=m.maxaspect;q["p95_tangent_aspect"]=m.p95aspect;q["minimum_scaled_jacobian"]=m.minjac;q["max_non_orthogonality_degrees"]=m.maxno;q["p95_non_orthogonality_degrees"]=m.p95no;q["max_wall_front_orthogonality_degrees"]=maxwall;q["p95_wall_front_orthogonality_degrees"]=p95(walls);py::dict r;r["accepted"]=true;r["status"]="native_tri_quad_authority_bound_sealed";r["requested_layers"]=req;r["actual_layers"]=actual;r["runtime_route"]="default_off";r["publication_eligible"]=false;r["route_calls"]=0;r["candidate_discarded"]=false;r["atomic_rollback"]=false;r["receipt_sealed"]=true;r["topology"]=topo;r["quality"]=q;r["triangle_output_count"]=triout;r["quad_output_count"]=quadout;r["source_faces_consumed"]=used.size();r["direct_lineage_count"]=outputs.size();r["receipt_digest"]="tri-quad-authority-v1|"+txt(a,"receipt_digest")+"|"+txt(o,"receipt_digest")+"|"+txt(l,"source_sha256")+"|"+cd+"|"+std::to_string(req);return r;
}
PYBIND11_MODULE(native_tri_quad_authority_bound_consumer,m){m.doc()="Private C++23 actual-v2 authority-bound Native TRI+QUAD consumer";m.def("validate_native_tri_quad_authority_bound",&validate,py::arg("authority_receipt"),py::arg("optimizer_receipt"),py::arg("source_ledger"),py::arg("producer_certificate"),py::arg("boundary_binding"),py::arg("baseline_points"),py::arg("baseline_triangles"),py::arg("baseline_quads"),py::arg("candidate_points"),py::arg("candidate_triangles"),py::arg("candidate_quads"),py::arg("requested_layers"),py::arg("actual_layers"),py::arg("baseline_artifact_digest"),py::arg("candidate_artifact_digest"),py::arg("quad_relabel"),py::arg("triangle_handoff"),py::arg("pair_plan_reordered"));}
