// Independent disk-authoritative OpenFOAM polyMesh quality oracle.
#include <pybind11/pybind11.h>
#include <algorithm>
#include <array>
#include <cctype>
#include <cmath>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <limits>
#include <set>
#include <sstream>
#include <string>
#include <utility>
#include <vector>
namespace py=pybind11;
namespace {
using V=std::array<double,3>; using F=std::vector<long long>;
struct A { std::vector<V> p; std::vector<F> f; std::vector<long long> o,n; std::vector<std::pair<long long,long long>> b; std::string e; };
V add(V a,const V& b){for(int i=0;i<3;++i)a[i]+=b[i];return a;}
V sub(const V&a,const V&b){return {a[0]-b[0],a[1]-b[1],a[2]-b[2]};}
V mul(const V&a,double s){return {a[0]*s,a[1]*s,a[2]*s};}
double dot(const V&a,const V&b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2];}
V cross(const V&a,const V&b){return {a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]};}
double mag(const V&a){return std::sqrt(dot(a,a));}
std::string uncomment(const std::string&s){std::string r;bool block=false,line=false;for(size_t i=0;i<s.size();++i){char c=s[i],d=i+1<s.size()?s[i+1]:'\0';if(block){if(c=='*'&&d=='/'){block=false;++i;}else if(c=='\n')r+='\n';continue;}if(line){if(c=='\n'){line=false;r+=c;}continue;}if(c=='/'&&d=='*'){block=true;++i;}else if(c=='/'&&d=='/'){line=true;++i;}else r+=c;}return r;}
std::vector<std::string> tok(const std::string&s){std::vector<std::string>r;std::string w;auto f=[&]{if(!w.empty()){r.push_back(w);w.clear();}};for(char c:uncomment(s)){if(std::isspace((unsigned char)c))f();else if(c=='('||c==')'||c=='{'||c=='}'||c==';'){f();r.emplace_back(1,c);}else w+=c;}f();return r;}
bool ll(const std::string&s,long long&v){if(s.empty())return false;char*e=nullptr;v=std::strtoll(s.c_str(),&e,10);return e!=s.c_str()&&*e=='\0';}
bool dd(const std::string&s,double&v){if(s.empty())return false;char*e=nullptr;v=std::strtod(s.c_str(),&e);return e!=s.c_str()&&*e=='\0'&&std::isfinite(v);}
bool locate(const std::vector<std::string>&t,const std::string&name,size_t&op,long long&count){for(size_t i=0;i+2<t.size();++i){if(t[i]!="object"||t[i+1]!=name)continue;size_t c=i+2;while(c<t.size()&&t[c]!=";")++c;if(c==t.size())return false;for(++c;c+1<t.size();++c){if(ll(t[c],count)&&t[c+1]=="("){op=c+1;return count>=0;}}}return false;}
bool points(const std::vector<std::string>&t,std::vector<V>&out){size_t op;long long n;if(!locate(t,"points",op,n))return false;size_t c=op+1;for(long long i=0;i<n;++i){if(c+4>=t.size()||t[c]!="(")return false;V p;if(!dd(t[c+1],p[0])||!dd(t[c+2],p[1])||!dd(t[c+3],p[2])||t[c+4]!=")")return false;out.push_back(p);c+=5;}return c<t.size()&&t[c]==")";}
bool faces(const std::vector<std::string>&t,std::vector<F>&out){size_t op;long long n;if(!locate(t,"faces",op,n))return false;size_t c=op+1;for(long long i=0;i<n;++i){if(c+1>=t.size())return false;long long m;if(!ll(t[c],m)||t[c+1]!="("||m<3)return false;c+=2;F f;for(long long j=0;j<m;++j){long long v;if(c>=t.size()||!ll(t[c],v))return false;f.push_back(v);++c;}if(c>=t.size()||t[c]!=")")return false;++c;out.push_back(std::move(f));}return c<t.size()&&t[c]==")";}
bool labels(const std::vector<std::string>&t,const std::string&name,std::vector<long long>&out){size_t op;long long n;if(!locate(t,name,op,n))return false;size_t c=op+1;for(long long i=0;i<n;++i){long long v;if(c>=t.size()||!ll(t[c],v))return false;out.push_back(v);++c;}return c<t.size()&&t[c]==")";}
bool boundary(const std::vector<std::string>&t,std::vector<std::pair<long long,long long>>&out){size_t x=t.size();for(size_t i=0;i+1<t.size();++i)if(t[i]=="object"&&t[i+1]=="boundary"){x=i;break;}if(x==t.size())return false;size_t c=x+2;while(c<t.size()&&t[c]!=";")++c;if(c==t.size())return false;long long np=0;for(++c;c<t.size()&&!ll(t[c],np);++c){}if(c==t.size()||np<0)return false;while(c<t.size()&&t[c]!="(")++c;if(c==t.size())return false;++c;for(long long k=0;k<np;++k){while(c<t.size()&&t[c]!="{")++c;if(c==t.size())return false;++c;int d=1;bool hn=false,hs=false;long long nf=0,sf=0;while(c<t.size()&&d){if(t[c]=="{")++d;else if(t[c]=="}")--d;else if(t[c]=="nFaces"&&c+1<t.size())hn=ll(t[c+1],nf);else if(t[c]=="startFace"&&c+1<t.size())hs=ll(t[c+1],sf);++c;}if(d||!hn||!hs||nf<0||sf<0)return false;out.emplace_back(sf,nf);}return c<t.size();}
bool readfile(const std::filesystem::path&p,std::string&s){if(std::filesystem::is_symlink(p)||!std::filesystem::is_regular_file(p))return false;std::ifstream in(p,std::ios::binary);if(!in)return false;std::ostringstream b;b<<in.rdbuf();s=b.str();return in.good()||in.eof();}
bool readmesh(const std::filesystem::path&r,A&a){std::array<std::string,5>x;std::array<std::string,5>n={"points","faces","owner","neighbour","boundary"};for(int i=0;i<5;++i)if(!readfile(r/n[i],x[i])){a.e="polymesh_file_missing:"+n[i];return false;}if(!points(tok(x[0]),a.p)||!faces(tok(x[1]),a.f)||!labels(tok(x[2]),"owner",a.o)||!labels(tok(x[3]),"neighbour",a.n)||!boundary(tok(x[4]),a.b)){a.e="polymesh_ascii_parse_failed";return false;}if(a.f.empty()||a.o.size()!=a.f.size()||a.n.size()>a.f.size()){a.e="polymesh_incidence_size_invalid";return false;}long long cells=0;for(auto&f:a.f){std::set<long long>u(f.begin(),f.end());if(u.size()!=f.size()){a.e="polymesh_face_degenerate";return false;}for(auto v:f)if(v<0||v>=static_cast<long long>(a.p.size())){a.e="polymesh_face_vertex_invalid";return false;}}for(auto c:a.o){if(c<0){a.e="polymesh_owner_invalid";return false;}cells=std::max(cells,c+1);}for(auto c:a.n)if(c<0||c>=cells){a.e="polymesh_neighbour_invalid";return false;}long long cur=a.n.size();for(auto[z,k]:a.b){if(z!=cur||k<0||z+k>static_cast<long long>(a.f.size())){a.e="polymesh_boundary_range_invalid";return false;}cur=z+k;}if(cur!=static_cast<long long>(a.f.size())){a.e="polymesh_boundary_coverage_gap";return false;}return true;}
struct M{double no=0,avg=0,is=0,bs=0,sk=0,ar=0,edge_ar=0;long long no_id=-1,sk_id=-1,ar_id=-1;bool finite=true;};
M quality(const A&a,long long nc){size_t nf=a.f.size(),ni=a.n.size();std::vector<V>fc(nf),fn(nf),cc(nc);std::vector<std::set<long long>>cv(nc);for(size_t i=0;i<nf;++i){V q{};for(auto v:a.f[i])q=add(q,a.p[v]);fc[i]=mul(q,1.0/a.f[i].size());V ar{};auto p0=a.p[a.f[i][0]];for(size_t j=1;j+1<a.f[i].size();++j)ar=add(ar,cross(sub(a.p[a.f[i][j]],p0),sub(a.p[a.f[i][j+1]],p0)));fn[i]=ar;cv[a.o[i]].insert(a.f[i].begin(),a.f[i].end());if(i<ni)cv[a.n[i]].insert(a.f[i].begin(),a.f[i].end());}M m;for(size_t i=0;i<cc.size();++i){if(cv[i].empty()){m.finite=false;continue;}for(auto v:cv[i])cc[i]=add(cc[i],a.p[v]);cc[i]=mul(cc[i],1.0/cv[i].size());}double sum=0;long long cnt=0;constexpr double pi=3.14159265358979323846;for(size_t i=0;i<nf;++i){double nm=mag(fn[i]);if(nm<=1e-30){m.finite=false;continue;}auto own=a.o[i];if(i<ni){auto nbr=a.n[i];V d=sub(cc[nbr],cc[own]);double dm=mag(d);if(dm<=1e-30){m.finite=false;continue;}double co=std::clamp(dot(d,fn[i])/(dm*nm),-1.0,1.0);double ang=std::acos(co)*180/pi;sum+=ang;++cnt;if(ang>m.no){m.no=ang;m.no_id=i;}V q=sub(fc[i],cc[own]);double t=dot(q,d)/(dm*dm);double s=mag(sub(fc[i],add(cc[own],mul(d,t))))/dm;if(!std::isfinite(s))m.finite=false;else if(s>m.is){m.is=s;m.sk_id=i;}}else{V u=mul(fn[i],1/nm),q=sub(fc[i],cc[own]);double nd=dot(q,u);double s=mag(sub(fc[i],add(cc[own],mul(u,nd))))/std::max(std::abs(nd),1e-30);if(!std::isfinite(s))m.finite=false;else m.bs=std::max(m.bs,s);}}m.avg=cnt?sum/cnt:0;m.sk=std::max(m.is,m.bs);std::vector<std::set<std::pair<long long,long long>>>ed(nc);for(size_t i=0;i<nf;++i){auto add_edges=[&](long long c){for(size_t j=0;j<a.f[i].size();++j)ed[c].insert(std::minmax(a.f[i][j],a.f[i][(j+1)%a.f[i].size()]));};add_edges(a.o[i]);if(i<ni)add_edges(a.n[i]);}for(size_t c=0;c<ed.size();++c){double lo=std::numeric_limits<double>::infinity(),hi=0;for(auto e:ed[c]){double l=mag(sub(a.p[e.second],a.p[e.first]));lo=std::min(lo,l);hi=std::max(hi,l);}if(!std::isfinite(lo)||lo<=1e-30){m.finite=false;continue;}double ar=hi/lo;if(ar>m.ar){m.ar=ar;m.ar_id=c;}}m.edge_ar=m.ar;for(size_t c=0;c<cv.size();++c){double lo=std::numeric_limits<double>::infinity(),hi=0;for(auto i=cv[c].begin();i!=cv[c].end();++i)for(auto j=cv[c].begin();j!=cv[c].end();++j){if(*i==*j)continue;double l=mag(sub(a.p[*j],a.p[*i]));lo=std::min(lo,l);hi=std::max(hi,l);}if(std::isfinite(lo)&&lo>1e-30){double ar=hi/lo;if(ar>m.ar){m.ar=ar;m.ar_id=c;}}}return m;}
py::dict audit(const std::string&rootarg){A a;auto r=std::filesystem::absolute(rootarg).lexically_normal();bool ok=std::filesystem::is_directory(r)&&readmesh(r,a);long long nc=0;for(auto c:a.o)nc=std::max(nc,c+1);for(auto c:a.n)nc=std::max(nc,c+1);M m;if(ok){m=quality(a,nc);ok=m.finite;}py::dict d;d["valid"]=ok;d["quality_pass"]=ok&&m.no<=50&&m.sk<=.5&&m.ar<=5;d["error"]=ok?"":a.e;d["n_points"]=a.p.size();d["n_faces"]=a.f.size();d["n_internal_faces"]=a.n.size();d["n_boundary_faces"]=a.f.size()-a.n.size();d["n_cells"]=nc;d["max_non_orthogonality"]=m.no;d["avg_non_orthogonality"]=m.avg;d["max_internal_skewness"]=m.is;d["max_boundary_skewness"]=m.bs;d["max_skewness"]=m.sk;d["max_aspect_ratio"]=m.ar;d["vertex_pair_aspect_ratio_exact"]=m.ar;d["topological_edge_aspect_ratio"]=m.edge_ar;d["worst_non_orthogonality_face"]=m.no_id;d["worst_skewness_face"]=m.sk_id;d["worst_aspect_cell"]=m.ar_id;return d;}
bool policy_hex64(const std::string& value){if(value.size()!=64)return false;return std::all_of(value.begin(),value.end(),[](char c){return (c>='0'&&c<='9')||(c>='a'&&c<='f')||(c>='A'&&c<='F');});}
py::dict audit_with_policy(const std::string& rootarg,const py::dict& policy){py::dict r=audit(rootarg);try{double no=py::cast<double>(policy["max_non_orthogonality"]);double sk=py::cast<double>(policy["max_skewness"]);double ar=py::cast<double>(policy["max_aspect_ratio"]);std::string digest=py::cast<std::string>(policy["policy_sha256"]);if(!std::isfinite(no)||!std::isfinite(sk)||!std::isfinite(ar)||no<0||sk<0||ar<0||!policy_hex64(digest))throw std::runtime_error("quality_policy_invalid");bool valid=py::cast<bool>(r["valid"]);bool passed=valid&&py::cast<double>(r["max_non_orthogonality"])<=no&&py::cast<double>(r["max_skewness"])<=sk&&py::cast<double>(r["max_aspect_ratio"])<=ar;r["quality_pass"]=passed;r["quality_policy_sealed"]=true;r["quality_policy_sha256"]=digest;r["quality_policy_max_non_orthogonality"]=no;r["quality_policy_max_skewness"]=sk;r["quality_policy_max_aspect_ratio"]=ar;return r;}catch(...){py::dict refusal;refusal["valid"]=false;refusal["quality_pass"]=false;refusal["quality_policy_sealed"]=false;refusal["error"]="quality_policy_invalid";return refusal;}}
}
PYBIND11_MODULE(native_tet_polymesh_quality,module){module.doc()="Independent disk-authoritative polyMesh quality oracle.";module.def("audit",&audit,py::arg("poly_mesh_root"));module.def("audit_with_policy",&audit_with_policy,py::arg("poly_mesh_root"),py::arg("quality_policy"));}
